./xmppclient1 test1@localhost sub &
./xmppclient1 test2@localhost sub &
./xmppclient1 test3@localhost sub &
./xmppclient1 test4@localhost sub &
./xmppclient1 test5@localhost sub &
./xmppclient1 test6@localhost sub &
./xmppclient1 test7@localhost sub &
./xmppclient1 test8@localhost sub &
./xmppclient1 test9@localhost sub &
./xmppclient1 test10@localhost sub &
